stages:
  - test
  - deploy

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 -m unittest discover tests/

production:
  only:
    - master
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 setup.py sdist
  - twine upload dist/* -u $PYPI_USER_NAME -p $PYPI_PASSWORD
